version: '2.1'
services:
  app:
    build:
      context: ./docker/app
    image: asgardcms/app:latest
    ports:
      - 8000:80
      - 443:443
    volumes:
      - .:/var/www/html:cached
    networks:
      - asgard_net
  redis:
    build:
      context: ./docker/redis
    image: asgardcms/redis:latest
    volumes:
      - redisdata:/data
    networks:
      - asgard_net

  mysql:
    build:
      context: ./docker/mysql
    image: asgardcms/mysql:latest
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: msita
      MYSQL_DATABASE: msita
      MYSQL_USER: msita
      MYSQL_PASSWORD: msita
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - asgard_net

  node:
    build:
      context: ./docker/node
    image: asgardcms/node:latest
    volumes:
      - .:/var/www/html

  blackfire:
    image: blackfire/blackfire
    environment:
      BLACKFIRE_SERVER_ID:
      BLACKFIRE_SERVER_TOKEN:
    networks:
    - asgard_net

volumes:
  redisdata:
    driver: local
  mysqldata:
    driver: local

networks:
  asgard_net:
    driver: bridge

